config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/contact'

	get 'customers/index'
  

  resources :customers
  resources :suppliers 
  resources :categories
  resources :sales
  resources :saledetails
  resources :products
  resources :purchases
  resources :purchasedetails

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :sale
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :saledetail
  has_many :purchasedetail
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :supplier
  has_many :purchasedetail
end

app/models/purchasedetail.rb
class Purchasedetail < ApplicationRecord
  belongs_to :purchase
  belongs_to :product
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :customer
  has_many :saledetail
end

app/models/saledetail.rb
class Saledetail < ApplicationRecord
  attr_accessor :customer_id
  attr_accessor :product_id
  belongs_to :sale
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :purchase
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
	@customers = Customer.all
	end
	
	def show
	@customer = Customer.find(params[:id])
	end
	
	def new
	@customer = Customer.new
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def create
	@customer = Customer.new(customer_params)
		if @customer.save
	redirect_to @customer
		else
	render 'new'
		end
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		redirect_to @customer
		else
		render 'edit'
		end
	end

	def destroy
	@customer = Customer.find(params[:id])
	@customer.destroy
	redirect_to customers_path
	end

	private
	def customer_params
	params.require(:customer).permit(:c_code, :c_name)
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	@products = Product.all
	end
	
	def show
	@product = Product.find(params[:id])
	end
	
	def new
	@product = Product.new
	end

	def edit
	@product = Product.find(params[:id])
	end

	def create
	@product = Product.new(product_params)
		if @product.save
	redirect_to @product
		else
	render 'new'
		end
	end

	def update
	@product = Product.find(params[:id])
		if @product.update(product_params)
		redirect_to @product
		else
		render 'edit'
		end
	end

	def destroy
	@product = Product.find(params[:id])
	@product.destroy
	redirect_to products_path
	end

	private
	def product_params
	params.require(:product).permit(:prod_code, :prod_name, :unit_price, :category_id)
	end

end

app/controllers/purchasedetails_controller.rb
class PurchasedetailsController < ApplicationController
	def index
	@purchasedetails = Purchasedetail.all
	end
	
	def show
	@purchasedetail = Purchasedetail.find(params[:id])
	end
	
	def new
	@purchasedetail = Purchasedetail.new
	end

	def edit
	@purchasedetail = Purchasedetail.find(params[:id])
	end

	def create
	@purchasedetail = Purchasedetail.new(purchasedetail_params)
		if @purchasedetail.save
	redirect_to @purchasedetail
		else
	render 'new'
		end
	end

	def update
	@purchasedetail = Purchasedetail.find(params[:id])
		if @purchasedetail.update(purchasedetail_params)
		redirect_to @purchasedetail
		else
		render 'edit'
		end
	end

	def destroy
	@purchasedetail = Purchasedetail.find(params[:id])
	@purchasedetail.destroy
	redirect_to purchasedetails_path
	end

	private
	def purchasedetail_params
	params.require(:purchasedetail).permit(:purchase_id, :prod_name, :prod_qty, :tp, :total)
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	def index
	@sales = Sale.all
	end
	
	def show
	@sale = Sale.find(params[:id])
	end
	
	def new
	@sale = Sale.new
	end

	def edit
	@sale = Sale.find(params[:id])
	end

	def create
	@sale = Sale.new(sale_params)
		if @sale.save
	redirect_to @sale
		else
	render 'new'
		end
	end

	def update
	@sale = Sale.find(params[:id])
		if @sale.update(sale_params)
		redirect_to @sale
		else
		render 'edit'
		end
	end

	def destroy
	@sale = Sale.find(params[:id])
	@sale.destroy
	redirect_to sales_path
	end

	private
	def sale_params
	params.require(:sale).permit(:inv_no, :inv_date, :customer_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchasedetails_helper.rb
module PurchasedetailsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/purchasedetails/_form.html.erb
<%= form_for @purchasedetail do |f| %>

<% if @purchasedetail.errors.any? %>

<div id="error_explanation">

<h2>

<%= pluralize(@purchasedetail.errors.count, "error") %> prohibited

this purchase detail from being saved:

</h2>
<ul>

<% @purchasedetail.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<p>

<%= f.label :Doc_no %><br>

<%= f.collection_select(:purchase_id, Purchase.all, :id, :doc_no, 
                  {include_blank: 'Select Document Number'})%>


</p>

<p>

<%= f.label :Product_Name %><br>

<%= f.text_field :prod_name %>

</p>

<p>

<%= f.label :Product_Qty %><br>

<%= f.number_field :prod_qty %>

</p>

<p>

<%= f.label :Trade_Price %><br>

<%= f.number_field :tp %>

</p>

<p>

<%= f.label :Total_Price %><br>

<%= f.number_field :total %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/purchasedetails/edit.html.erb
<h1>Edit Purchsae Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', purchasedetails_path %>

app/views/purchasedetails/index.html.erb
<table>
	<tr>
		<th>Doc#</th>
		<th>Product_Name</th>
		<th>Product_Qty</th>
		<th>Trade_Price</th>
		<th>Total_Price</th>
		<th colspan="4"></th>
	</tr>
		<% @purchasedetails.each do |purchasedetail| %>
	<tr>
		<td><%= purchasedetail.purchase.doc_no %></td>
		<td><%= purchasedetail.prod_name %></td>
		<td><%= purchasedetail.prod_qty %></td>
		<td><%= purchasedetail.tp %></td>
		<td><%= purchasedetail.total %></td>
		<td><%= link_to 'Show', purchasedetail_path(purchasedetail) %></td>
		<td><%= link_to 'Edit', edit_purchasedetail_path(purchasedetail) %></td>
		<td><%= link_to 'Delete', purchasedetail_path(purchasedetail), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
	</tr>
		
		<% end %>
</table>

app/views/purchasedetails/new.html.erb
<h1>New Purchase Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', purchasedetails_path %>

app/views/purchasedetails/show.html.erb
<h1> Purchase Detail List </h1> 
 <p>
	<strong>Doc_no:</strong>
		<%= @purchasedetail.purchase.doc_no %>
 </p>
 <p>
	<strong>Prod_Name:</strong>
		<%= @purchasedetail.prod_name %>
 </p>
 
  <p>
	<strong>Product_Qty:</strong>
		<%= @purchasedetail.prod_qty %>
 </p>
 
 <p>
	<strong>Trade_Price:</strong>
		<%= @purchasedetail.tp %>
 </p>
 
  <p>
	<strong>Total:</strong>
		<%= @purchasedetail.total %>
 </p>
	<%= link_to 'Back', purchasedetails_path %>