config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/contact'

	get 'customers/index'
  

  resources :customers
  resources :suppliers 
  resources :categories
  resources :sales
  resources :saledetails
  resources :products
  resources :purchases
  resources :purchasedetails

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :sale
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :saledetail
  has_many :purchasedetail
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :supplier
  has_many :purchasedetail
end

app/models/purchasedetail.rb
class Purchasedetail < ApplicationRecord
  belongs_to :purchase
  belongs_to :product
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :customer
  has_many :saledetail
end

app/models/saledetail.rb
class Saledetail < ApplicationRecord
  attr_accessor :customer_id
  attr_accessor :product_id
  belongs_to :sale
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :purchase
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
	@customers = Customer.all
	end
	
	def show
	@customer = Customer.find(params[:id])
	end
	
	def new
	@customer = Customer.new
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def create
	@customer = Customer.new(customer_params)
		if @customer.save
	redirect_to @customer
		else
	render 'new'
		end
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		redirect_to @customer
		else
		render 'edit'
		end
	end

	def destroy
	@customer = Customer.find(params[:id])
	@customer.destroy
	redirect_to customers_path
	end

	private
	def customer_params
	params.require(:customer).permit(:c_code, :c_name)
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	@products = Product.all
	end
	
	def show
	@product = Product.find(params[:id])
	end
	
	def new
	@product = Product.new
	end

	def edit
	@product = Product.find(params[:id])
	end

	def create
	@product = Product.new(product_params)
		if @product.save
	redirect_to @product
		else
	render 'new'
		end
	end

	def update
	@product = Product.find(params[:id])
		if @product.update(product_params)
		redirect_to @product
		else
		render 'edit'
		end
	end

	def destroy
	@product = Product.find(params[:id])
	@product.destroy
	redirect_to products_path
	end

	private
	def product_params
	params.require(:product).permit(:prod_code, :prod_name, :unit_price, :category_id)
	end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
	def index
	@purchases = Purchase.all
	end
	
	def show
	@purchase = Purchase.find(params[:id])
	end
	
	def new
	@purchase = Purchase.new
	end

	def edit
	@purchase = Purchase.find(params[:id])
	end

	def create
	@purchase = Purchase.new(purchase_params)
		if @purchase.save
	redirect_to @purchase
		else
	render 'new'
		end
	end

	def update
	@purchase = Purchase.find(params[:id])
		if @purchase.update(purchase_params)
		redirect_to @purchase
		else
		render 'edit'
		end
	end

	def destroy
	@purchase = Purchase.find(params[:id])
	@purchase.destroy
	redirect_to purchases_path
	end

	private
	def purchase_params
	params.require(:purchase).permit(:doc_no, :doc_date, :vehicle_no, :supplier_id)
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	def index
	@sales = Sale.all
	end
	
	def show
	@sale = Sale.find(params[:id])
	end
	
	def new
	@sale = Sale.new
	end

	def edit
	@sale = Sale.find(params[:id])
	end

	def create
	@sale = Sale.new(sale_params)
		if @sale.save
	redirect_to @sale
		else
	render 'new'
		end
	end

	def update
	@sale = Sale.find(params[:id])
		if @sale.update(sale_params)
		redirect_to @sale
		else
		render 'edit'
		end
	end

	def destroy
	@sale = Sale.find(params[:id])
	@sale.destroy
	redirect_to sales_path
	end

	private
	def sale_params
	params.require(:sale).permit(:inv_no, :inv_date, :customer_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchasedetails_helper.rb
module PurchasedetailsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/customers/_form.html.erb
<%= form_for @customer do |f| %>

<% if @customer.errors.any? %>

<div id="error_explanation">

<h2>

<%= pluralize(@customer.errors.count, "error") %> prohibited

this customer from being saved:

</h2>
<ul>

<% @customer.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<p>

<%= f.label :Code %><br>

<%= f.number_field :c_code %>

</p>

<p>

<%= f.label :Name %><br>

<%= f.text_field :c_name %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<table>
	<tr>
		<th>Code</th>
		<th>Name</th>
		<th colspan="2"></th>
	</tr>
		<% @customers.each do |customer| %>
	<tr>
		<td><%= customer.c_code %></td>
		<td><%= customer.c_name %></td>
		<td><%= link_to 'Show', customer_path(customer) %></td>
		<td><%= link_to 'Edit', edit_customer_path(customer) %></td>
		<td><%= link_to 'Delete', customer_path(customer), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
	</tr>
		
		<% end %>
</table>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p>
<strong>Code:</strong>
<%= @customer.c_code %>
</p>
<p>
<strong>Name:</strong>
<%= @customer.c_name %>
</p>
<%= link_to 'Back', customers_path %>

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

<% if @product.errors.any? %>

<div id="error_explanation">

<h2>

<%= pluralize(@product.errors.count, "error") %> prohibited

this product from being saved:

</h2>
<ul>

<% @product.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<p>

<%= f.label :Code %><br>

<%= f.number_field :prod_code %>

</p>

<p>

<%= f.label :Name %><br>

<%= f.text_field :prod_name %>

</p>

	<p>

	<%= f.label :Price %><br>

	<%= f.number_field :unit_price %>

	</p>

<p>

<%= f.label :Category %><br>

<%= f.collection_select(:category_id, Category.all, :id, :title, 
                  {include_blank: 'Select category'})%>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Prod</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<table>
	<tr>
		<th>Code#</th>
		<th>Name</th>
		<th>Price</th>
		<th>Category</th>
		<th colspan="4"></th>
	</tr>
		<% @products.each do |product| %>
	<tr>
		<td><%= product.prod_code %></td>
		<td><%= product.prod_name %></td>
		<td><%= product.unit_price %></td>
		<td><%= product.category.title %></td>
		<td><%= link_to 'Show', product_path(product) %></td>
		<td><%= link_to 'Edit', edit_product_path(product) %></td>
		<td><%= link_to 'Delete', product_path(product), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
	</tr>
		
		<% end %>
</table>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<h1> Products List </h1> 
 <p>
	<strong>Code:</strong>
		<%= @product.prod_code %>
 </p>
 <p>
	<strong>Name:</strong>
		<%= @product.prod_name %>
 </p>
 
 <p>
	<strong>Price:</strong>
		<%= @product.unit_price %>
 </p> 
  <p>
	<strong>Category:</strong>
		<%= @product.category.title %>
 </p>
	<%= link_to 'Back', products_path %>

app/views/sales/_form.html.erb
<%= form_for @sale do |f| %>

<% if @sale.errors.any? %>

<div id="error_explanation">

<h2>

<%= pluralize(@sale.errors.count, "error") %> prohibited

this sale from being saved:

</h2>
<ul>

<% @sale.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<p>

<%= f.label :Invoice_no %><br>

<%= f.number_field :inv_no %>

</p>

<p>

<%= f.label :Date %><br>

<%= f.date_select :inv_date %>

</p>

<p>

<%= f.label :Customer %><br>

<%= f.collection_select(:customer_id, Customer.all, :id, :c_name, 
                  {include_blank: 'Select customer'})%>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/sales/edit.html.erb
<h1>Edit Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/index.html.erb
<table>
	<tr>
		<th>Invoice#</th>
		<th>Date</th>
		<th>Customer</th>
		<th colspan="4"></th>
	</tr>
		<% @sales.each do |sale| %>
	<tr>
		<td><%= sale.inv_no %></td>
		<td><%= sale.inv_date %></td>
		<td><%= sale.customer.c_name %></td>
		<td><%= link_to 'Show', sale_path(sale) %></td>
		<td><%= link_to 'Edit', edit_sale_path(sale) %></td>
		<td><%= link_to 'Delete', sale_path(sale), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
	</tr>
		
		<% end %>
</table>

app/views/sales/new.html.erb
<h1>New Sale</h1>

<%= render 'form' %>

<%= link_to 'Back', sales_path %>

app/views/sales/show.html.erb
<h1> Sale List </h1> 
 <p>
	<strong>Invoice_no:</strong>
		<%= @sale.inv_no %>
 </p>
 <p>
	<strong>Date:</strong>
		<%= @sale.inv_date %>
 </p>
 
  <p>
	<strong>Customer:</strong>
		<%= @sale.customer.c_name %>
 </p>
	<%= link_to 'Back', sales_path %>