config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/contact'

	get 'customers/index'
  

  resources :customers
  resources :suppliers 
  resources :categories
  resources :sales
  resources :saledetails
  resources :products
  resources :purchases
  resources :purchasedetails

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :sale
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :saledetail
  has_many :purchasedetail
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :supplier
  has_many :purchasedetail
end

app/models/purchasedetail.rb
class Purchasedetail < ApplicationRecord
  belongs_to :purchase
  belongs_to :product
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :customer
  has_many :saledetail
end

app/models/saledetail.rb
class Saledetail < ApplicationRecord
  attr_accessor :customer_id
  attr_accessor :product_id
  belongs_to :sale
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :purchase
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
	@customers = Customer.all
	end
	
	def show
	@customer = Customer.find(params[:id])
	end
	
	def new
	@customer = Customer.new
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def create
	@customer = Customer.new(customer_params)
		if @customer.save
	redirect_to @customer
		else
	render 'new'
		end
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		redirect_to @customer
		else
		render 'edit'
		end
	end

	def destroy
	@customer = Customer.find(params[:id])
	@customer.destroy
	redirect_to customers_path
	end

	private
	def customer_params
	params.require(:customer).permit(:c_code, :c_name)
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	@products = Product.all
	end
	
	def show
	@product = Product.find(params[:id])
	end
	
	def new
	@product = Product.new
	end

	def edit
	@product = Product.find(params[:id])
	end

	def create
	@product = Product.new(product_params)
		if @product.save
	redirect_to @product
		else
	render 'new'
		end
	end

	def update
	@product = Product.find(params[:id])
		if @product.update(product_params)
		redirect_to @product
		else
		render 'edit'
		end
	end

	def destroy
	@product = Product.find(params[:id])
	@product.destroy
	redirect_to products_path
	end

	private
	def product_params
	params.require(:product).permit(:prod_code, :prod_name, :unit_price, :category_id)
	end

end

app/controllers/saledetails_controller.rb
class SaledetailsController < ApplicationController
	def index
	@saledetails = Saledetail.all
	end
	
	def show
	@saledetail = Saledetail.find(params[:id])
	end
	
	def new
	@saledetail = Saledetail.new
	end

	def edit
	@saledetail = Saledetail.find(params[:id])
	end

	def create
	@saledetail = Saledetail.new(saledetail_params)
		if @saledetail.save
	redirect_to @saledetail
		else
	render 'new'
		end
	end

	def update
	@saledetail = Saledetail.find(params[:id])
		if @saledetail.update(saledetail_params)
		redirect_to @saledetail
		else
		render 'edit'
		end
	end

	def destroy
	@saledetail = Saledetail.find(params[:id])
	@saledetail.destroy
	redirect_to saledetails_path
	end

	private
	def saledetail_params
	params.require(:saledetail).permit(:sale_id, :customer_id, :c_name, :product_id, :prod_name, :prod_qty, :gross_sale, :tax, :discount, :net_sale)
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	def index
	@sales = Sale.all
	end
	
	def show
	@sale = Sale.find(params[:id])
	end
	
	def new
	@sale = Sale.new
	end

	def edit
	@sale = Sale.find(params[:id])
	end

	def create
	@sale = Sale.new(sale_params)
		if @sale.save
	redirect_to @sale
		else
	render 'new'
		end
	end

	def update
	@sale = Sale.find(params[:id])
		if @sale.update(sale_params)
		redirect_to @sale
		else
		render 'edit'
		end
	end

	def destroy
	@sale = Sale.find(params[:id])
	@sale.destroy
	redirect_to sales_path
	end

	private
	def sale_params
	params.require(:sale).permit(:inv_no, :inv_date, :customer_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchasedetails_helper.rb
module PurchasedetailsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/saledetails/_form.html.erb
<%= form_for @saledetail do |f| %>

<% if @saledetail.errors.any? %>

<div id="error_explanation">

<h2>

<%= pluralize(@saledetail.errors.count, "error") %> prohibited

this sale detail from being saved:

</h2>
<ul>

<% @saledetail.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<p>

<%= f.label :Invoice_no %><br>

<%= f.collection_select(:sale_id, Sale.all, :id, :inv_no, 
                  {include_blank: 'Select invoice number'})%>


</p>

<p>

<%= f.label :Customer %><br>

<%= f.collection_select(:customer_id, Customer.all, :id, :c_name, 
                  {include_blank: 'Select customer'})%>

</p>

<p>

<%= f.label :Product_Name %><br>

<%= f.collection_select(:prod_qty, Product.all, :id, :prod_name, 
                  {include_blank: 'Select product'})%>


</p>

<p>

<%= f.label :Product_Qty %><br>

<%= f.number_field :prod_qty %>

</p>

<p>

<%= f.label :Gross_Sale %><br>

<%= f.number_field :gross_sale %>

</p>

<p>

<%= f.label :Tax %><br>

<%= f.number_field :tax %>

</p>

<p>

<%= f.label :Discount %><br>

<%= f.number_field :discount %>

</p>

<p>

<%= f.label :Net_Sale %><br>

<%= f.number_field :net_sale %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/saledetails/edit.html.erb
<h1>Edit Sale Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', saledetails_path %>

app/views/saledetails/index.html.erb
<table>
	<tr>
		<th>Invoice#</th>
		<th>Customer</th>
		<th>Product_Name</th>
		<th>Product_Qty</th>
		<th>Gross_Sale</th>
		<th>Tax</th>
		<th>Discount</th>
		<th>Net_Sale</th>
		<th colspan="4"></th>
	</tr>
		<% @saledetails.each do |saledetail| %>
	<tr>
		<td><%= saledetail.sale.inv_no %></td>
		<td><%= saledetail.sale.customer.c_name %></td>
		<td><%= saledetail.prod_name %></td>
		<td><%= saledetail.prod_qty %></td>
		<td><%= saledetail.gross_sale %></td>
		<td><%= saledetail.tax %></td>
		<td><%= saledetail.discount %></td>
		<td><%= saledetail.net_sale %></td>
		<td><%= link_to 'Show', saledetail_path(saledetail) %></td>
		<td><%= link_to 'Edit', edit_saledetail_path(saledetail) %></td>
		<td><%= link_to 'Delete', saledetail_path(saledetail), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
	</tr>
		
		<% end %>
</table>

app/views/saledetails/new.html.erb
<h1>New Sale Detail</h1>

<%= render 'form' %>

<%= link_to 'Back', saledetails_path %>

app/views/saledetails/show.html.erb
<h1> Sale Detail </h1> 
 <p>
	<strong>Invoice_no:</strong>
		<%= @saledetail.sale.inv_no %>
 </p>
 <p>
	<strong>Customer_Name:</strong>
		<%= @saledetail.sale.customer.c_name %>
 </p>
 
  <p>
	<strong>Product_Name:</strong>
		<%= @saledetail.product.prod_name %>
 </p>
 
 <p>
	<strong>Product_Qty:</strong>
		<%= @saledetail.prod_qty %>
 </p>
 
   <p>
	<strong>Gross:</strong>
		<%= @saledetail.gross_sale %>
 </p>
 
 <p>
	<strong>Tax:</strong>
		<%= @saledetail.tax %>
 </p>
 
 <p>
	<strong>Discount:</strong>
		<%= @saledetail.discount %>
 </p>
 
 <p>
	<strong>Net_Sale:</strong>
		<%= @saledetail.net_sale %>
 </p> 
	<%= link_to 'Back', saledetails_path %>