config/routes.rb
Rails.application.routes.draw do

  get 'static_pages/home'
  root 'static_pages#home'

  get 'static_pages/about'

  get 'static_pages/contact'

	get 'customers/index'
  

  resources :customers
  resources :suppliers 
  resources :categories
  resources :sales
  resources :saledetails
  resources :products
  resources :purchases
  resources :purchasedetails

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :product
end

app/models/customer.rb
class Customer < ApplicationRecord
	has_many :sale
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :saledetail
  has_many :purchasedetail
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :supplier
  has_many :purchasedetail
end

app/models/purchasedetail.rb
class Purchasedetail < ApplicationRecord
  belongs_to :purchase
  belongs_to :product
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :customer
  has_many :saledetail
end

app/models/saledetail.rb
class Saledetail < ApplicationRecord
  attr_accessor :customer_id
  attr_accessor :product_id
  belongs_to :sale
  belongs_to :product
end

app/models/supplier.rb
class Supplier < ApplicationRecord
	has_many :purchase
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
	@categories = Category.all
	end
	
	def show
	@category = Category.find(params[:id])
	end
	
	def new
	@category = Category.new
	end

	def edit
	@category = Category.find(params[:id])
	end

	def create
	@category = Category.new(category_params)
		if @category.save
	redirect_to @category
		else
	render 'new'
		end
	end

	def update
	@category = Category.find(params[:id])
		if @category.update(category_params)
		redirect_to @category
		else
		render 'edit'
		end
	end

	def destroy
	@category = Category.find(params[:id])
	@category.destroy
	redirect_to categories_path
	end

	private
	def category_params
	params.require(:category).permit(:cat_code, :title, :detail)
	end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
	def index
	@customers = Customer.all
	end
	
	def show
	@customer = Customer.find(params[:id])
	end
	
	def new
	@customer = Customer.new
	end

	def edit
	@customer = Customer.find(params[:id])
	end

	def create
	@customer = Customer.new(customer_params)
		if @customer.save
	redirect_to @customer
		else
	render 'new'
		end
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		redirect_to @customer
		else
		render 'edit'
		end
	end

	def destroy
	@customer = Customer.find(params[:id])
	@customer.destroy
	redirect_to customers_path
	end

	private
	def customer_params
	params.require(:customer).permit(:c_code, :c_name)
	end
	
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
	@products = Product.all
	end
	
	def show
	@product = Product.find(params[:id])
	end
	
	def new
	@product = Product.new
	end

	def edit
	@product = Product.find(params[:id])
	end

	def create
	@product = Product.new(product_params)
		if @product.save
	redirect_to @product
		else
	render 'new'
		end
	end

	def update
	@product = Product.find(params[:id])
		if @product.update(product_params)
		redirect_to @product
		else
		render 'edit'
		end
	end

	def destroy
	@product = Product.find(params[:id])
	@product.destroy
	redirect_to products_path
	end

	private
	def product_params
	params.require(:product).permit(:prod_code, :prod_name, :unit_price, :category_id)
	end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
	def index
	@sales = Sale.all
	end
	
	def show
	@sale = Sale.find(params[:id])
	end
	
	def new
	@sale = Sale.new
	end

	def edit
	@sale = Sale.find(params[:id])
	end

	def create
	@sale = Sale.new(sale_params)
		if @sale.save
	redirect_to @sale
		else
	render 'new'
		end
	end

	def update
	@sale = Sale.find(params[:id])
		if @sale.update(sale_params)
		redirect_to @sale
		else
		render 'edit'
		end
	end

	def destroy
	@sale = Sale.find(params[:id])
	@sale.destroy
	redirect_to sales_path
	end

	private
	def sale_params
	params.require(:sale).permit(:inv_no, :inv_date, :customer_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/purchasedetails_helper.rb
module PurchasedetailsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/suppliers_helper.rb
module SuppliersHelper
end

app/views/categories/_form.html.erb
<%= form_for @category do |f| %>

<% if @category.errors.any? %>

<div id="error_explanation">

<h2>

<%= pluralize(@category.errors.count, "error") %> prohibited

this category from being saved:

</h2>
<ul>

<% @category.errors.full_messages.each do |msg| %>

<li><%= msg %></li>

<% end %>

</ul>

</div>

<% end %>

<p>

<%= f.label :Code %><br>

<%= f.number_field :cat_code %>

</p>

<p>

<%= f.label :Title %><br>

<%= f.text_field :title %>

</p>

<p>

<%= f.label :Detail %><br>

<%= f.text_area :detail %>

</p>

<p>

<%= f.submit %>

</p>

<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<table>
	<tr>
		<th>Code</th>
		<th>Title</th>
		<th>Detail</th>
		<th colspan="2"></th>
	</tr>
		<% @categories.each do |category| %>
	<tr>
		<td><%= category.cat_code %></td>
		<td><%= category.title %></td>
		<td><%= category.detail %></td>
		<td><%= link_to 'Show', category_path(category) %></td>
		<td><%= link_to 'Edit', edit_category_path(category) %></td>
		<td><%= link_to 'Delete', category_path(category), method: :delete, data: {confirm: 'Are You Sure?'} %></td>
	</tr>
		
		<% end %>
</table>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h1> Categories List </h1> 
 <p>
	<strong>Code:</strong>
		<%= @category.cat_code %>
 </p>
 <p>
	<strong>Title:</strong>
		<%= @category.title %>
 </p>
 
  <p>
	<strong>Detail:</strong>
		<%= @category.detail %>
 </p>
	<%= link_to 'Back', categories_path %>